services:
  electric-shdl:
    image: electricsql/electric:1.7.7
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DATABASE_URL: postgresql://chris:eureka31@host.docker.internal:5432/shdl
      ELECTRIC_INSECURE: "true"
    ports:
      - "3016:3000"
