// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!WQQOPOOOVOPO'#C^OOOO'#Cb'#CbQQOPOOO[OPO,58xOOOO-E6`-E6`OOOO'#C`'#C`OdOPO1G.dOOOO7+$O7+$O",
  stateData: "i~ORPO~OWSO~ORUOTUO~OXWO~O",
  goto: "eVPPWP[P_TQORRVSQRORTR",
  nodeNames: "⚠ Program Statement Identifier Expression Number",
  maxTerm: 9,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "!P~RT!Q![b!]!^j!_!`o!c!}t#T#ot~gPT~!Q![b~oOX~~tOW~~yQR~!c!}t#T#ot",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
